language: clojure

script:
- lein cljsbuild once
- lein test

after_success:
- lein cloverage --codecov
- bash <(curl -s https://codecov.io/bash) -f target/coverage/codecov.json

deploy:
  provider: pages
  skip-cleanup: true
  local-dir: resources/public
  github-token: $GITHUB_PAGES_TOKEN
  keep-history: true
  on:
    branch: master